import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "./Components/Providers"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZK Voting with Cairo",  // Create Next App
  description: "Generating the next ZK-Verified Voting...",  // Generated by create next app
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
          </Providers>
          </body>
    </html>
  );
}




/** 
  TO BE DOUBLE CHECKED!

// STEP 1: User opens website
// Browser loads layout.tsx FIRST

// STEP 2: layout.tsx renders
<Providers>  // ← Creates wallet system
  // Providers now WAITING for page.tsx
</Providers>

// STEP 3: Next.js injects page.tsx into {children}
<Providers>
  <page.tsx />  // ← Injected here
</Providers>

// STEP 4: page.tsx renders
<Providers>
  <div>
    <WalletBar />      // ← Renders connect button
    <Counter />        // ← Renders counter display
  </div>
</Providers>

// STEP 5: User clicks "Connect Wallet"
// WalletBar calls a function from Providers
// Providers opens Argent X popup

// STEP 6: User approves connection
// Providers updates its internal state
// WalletBar re-renders with "Connected: 0x123..."
// Counter can now read user's address





**/
